# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2cd3eb58ed85704a7a250d70213d4f0b"
name = "MerchPreview"
application_url = "https://merchpreview-3e72234e1c60.herokuapp.com/"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_customer_events,read_cart_transforms,write_cart_transforms,read_checkout_branding_settings,write_checkout_branding_settings,read_customers,write_customers,read_customer_merge,write_customer_merge,read_delivery_customizations,write_delivery_customizations,read_price_rules,write_price_rules,read_discounts,write_discounts,write_draft_orders,read_draft_orders,read_files,write_files,read_fulfillments,write_fulfillments,read_gift_cards,write_gift_cards,write_inventory,read_inventory,read_legal_policies,read_locales,write_locales,write_locations,read_locations,write_marketing_events,read_marketing_events,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_online_store_pages,read_orders,write_orders,write_pixels,read_products,write_products,read_publications,write_publications,write_reports,read_reports,read_resource_feedbacks,write_resource_feedbacks,read_script_tags,write_script_tags,read_shipping,write_shipping,read_shopify_payments_payouts,read_shopify_payments_disputes,read_content,write_content,read_themes,write_themes,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders"
optional_scopes = []
use_legacy_install_flow = false


[auth]
redirect_urls = [
  "https://merchpreview-3e72234e1c60.herokuapp.com//auth/callback",
  "https://merchpreview-3e72234e1c60.herokuapp.com//auth/shopify/callback",
  "https://merchpreview-3e72234e1c60.herokuapp.com//api/auth/callback"
]

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]


[build]
automatically_update_urls_on_dev = true


[app_proxy]
url = "https://merchpreview-3e72234e1c60.herokuapp.com/customapi"
subpath = "proxy"
prefix = "apps"
